// Code generated by a tool. DO NOT EDIT.

package azg010generated

import (
	gen "strings" // want `import alias "gen" is not needed, the package name "strings" does not clash`
)

func generated() {
	_ = gen.ToUpper("x")
}
